### ISSUE TITLE
0.4.0 not deployed to clojars

### ISSUE THREAD

**Issue by kelsey-sorrels** [rogerallen/hello_lwjgl#9]
I'd like to make aaron-santos/zaffre depend on the official release of hello_lwjgl 0.4.0. Could you deploy it to clojars?

**Comment by rogerallen** [comment]
That looks like a cool project.  

I think I would suggest just taking the interesting bits from this project's project.clj and incorporating them in your project.clj rather than depending on this project.  That way it is more clear & direct & controllable exactly what you install.  Make sense?

**Comment by kelsey-sorrels** [comment]
Perfect sense. Thank you for the great suggestion. I appreciate it.
